app/app_base/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from app_base import views
from calculation_engine.urls import api_router as ce_api_router, upload_detail, upload_list
from calculation_engine import urls as ce_page_urls
from django.views.generic import TemplateView
from rest_framework.schemas import get_schema_view

# # Imports for serving static files in development mode
# # ref: https://docs.djangoproject.com/en/4.2/howto/static-files/#serving-static-files-during-development
# from django.conf import settings
# from django.conf.urls.static import static

from calculation_engine.log import get_logger
logger = get_logger(__name__)


router = routers.DefaultRouter()
router.register(r'user', views.UserViewSet)

urlpatterns = [
    path('', views.HomePageView, name='home'),
    path('token', views.CustomAuthToken.as_view(), name='token'),
    path('admin/', admin.site.urls, name='admin'),
    path('oidc/', include('mozilla_django_oidc.urls')),
    path('users/', views.UserListView.as_view(), name='user-list-page'),
    path('ce/', include(ce_page_urls)),
    path('api/v0/', include(router.urls), name='base-api'),
    path('api/v0/token/', views.get_token, name='token-api'),
    path('api/v0/ce/', include(ce_api_router.urls)),
    path('api/v0/ce/upload/', upload_list, name='upload-list'),
    path('api/v0/ce/upload/<str:pk>/', upload_detail, name='upload-detail'),
]
# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    # Use the `get_schema_view()` helper to add a `SchemaView` to project URLs.
    #   * `title` and `description` parameters are passed to `SchemaGenerator`.
    #   * Provide view name for use with `reverse()`.
    path('openapi/', get_schema_view(
        title="MUSES Calculation Engine API",
        description="API for the MUSES Calculation Engine",
        version="1.0.0",
        patterns=urlpatterns,
        public=True,
        # urlconf='app_base.urls',
    ), name='openapi-schema'),
    # ...
    # Route TemplateView to serve Swagger UI template.
    #   * Provide `extra_context` with view name of `SchemaView`.
    path('swagger-ui/', TemplateView.as_view(
        template_name='calculation_engine/swagger-ui.html',
        extra_context={'schema_url': 'openapi-schema'}
    ), name='swagger-ui'),
]

# Django Silk profiler (https://github.com/jazzband/django-silk)
urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

app/calculation_engine/urls.py
from calculation_engine import views
from rest_framework import routers
from django.urls import path
from django.contrib.auth.decorators import login_required

api_router = routers.DefaultRouter()
api_router.register(r'job', views.JobViewSet, basename='job')

upload_list = views.UploadViewSet.as_view({
    'get': 'list',
    'put': 'create'
})
upload_detail = views.UploadViewSet.as_view({
    'get': 'retrieve',
    'patch': 'partial_update',
    'delete': 'destroy'
})
jobfile_detail = views.JobFileDownloadViewSet.as_view({
    'get': 'download',
    'post': 'download',
})
urlpatterns = [
    path('jobs/', login_required(views.JobListView.as_view()), name='job-page'),
    path('uploads/', login_required(views.UploadListView.as_view()), name='upload-page'),
    path('metrics/', login_required(views.MetricsListView.as_view()), name='metrics-page'),
    path('download/<uuid:job_id>/<path:file_path>', jobfile_detail, name='download-job-file'),
    path('download/<uuid:upload_id>', views.UploadDownloadViewSet.as_view({
        'get': 'download',
        'post': 'download',
    }), name='download-upload'),
]

app/calculation_engine/models.py
from django.db import models
import uuid
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User

from calculation_engine.log import get_logger
logger = get_logger(__name__)


class Job(models.Model):
    class Meta:
        # -created means newest first
        # to avoid DRF pagination UnorderedObjectListWarning
        ordering = ['-created']
        # db_table = 'ce_jobs'
        verbose_name = _('job')
        verbose_name_plural = _('jobs')

    class JobStatus(models.TextChoices):
        '''
        Django docs: https://docs.djangoproject.com/en/5.0/ref/models/fields/#enumeration-types
        '''

        # Use the built-in Celery states
        PENDING = 'PENDING', _('Pending')
        STARTED = 'STARTED', _('Started')
        SUCCESS = 'SUCCESS', _('Success')
        FAILURE = 'FAILURE', _('Failure')
        RETRY = 'RETRY', _('Retry')
        REVOKED = 'REVOKED', _('Revoked')

    name = models.TextField(blank=True)
    description = models.TextField(blank=True)
    owner = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    error_info = models.TextField(blank=True)
    config = models.JSONField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Time Created')
    modified = models.DateTimeField(auto_now=True, verbose_name='Last Modified')
    uuid = models.UUIDField(
        default=uuid.uuid4,
        unique=True,
        db_index=True,
        primary_key=True
    )
    status = models.CharField(
        max_length=10,
        choices=JobStatus.choices,
        default=JobStatus.PENDING,
    )
    saved = models.BooleanField(default=False, null=False, blank=True)
    public = models.BooleanField(default=False, null=False, blank=True)

    def __str__(self):
        ret = f'job: {self.uuid}, owner: {self.owner}, status: {self.status}'
        ret += f', created: {self.created}, config: {self.config}'
        return ret


class Metrics(models.Model):
    time_collected = models.DateTimeField(auto_now_add=True, verbose_name='Time Collected')
    jobs_total = models.IntegerField(null=False, blank=False)
    jobs_success = models.IntegerField(null=False, blank=False)
    jobs_failure = models.IntegerField(null=False, blank=False)
    users_count = models.IntegerField(null=False, blank=False)
    users_active = models.IntegerField(null=False, blank=False)
    uploads_total = models.IntegerField(null=False, blank=False)
    uploads_size = models.IntegerField(null=False, blank=False)
    job_files_total = models.IntegerField(null=False, blank=False)
    job_files_size = models.IntegerField(null=False, blank=False)


def upload_dir_path(instance, filename):
    return f'''{instance.uuid}/{instance.path}'''


class Upload(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, db_index=True, primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    path = models.CharField(max_length=None, default='')
    description = models.TextField(blank=True)
    file = models.FileField(upload_to=upload_dir_path, null=False, blank=False)
    owner = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    public = models.BooleanField(default=False, null=False, blank=True)
    size = models.IntegerField(null=False, blank=False, default=0) # Size of the stored file in bytes

    def __str__(self):
        ret = f'path: {self.path}, description: {self.description}, public: {self.public}'
        ret += f', created: {self.created}'
        return ret


class JobFile(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    path = models.CharField(max_length=None, default='')
    size = models.IntegerField(null=False, blank=False, default=0) # Size of the stored file in bytes


def update_job_state(job_id, state, error_info=''):
    logger.debug(f'''Updating job "{job_id}" state to: "{state}"...''')
    job = Job.objects.get(uuid__exact=job_id)
    job.status = state
    job.error_info = error_info
    job.save()

app/calculation_engine/views.py
from rest_framework.response import Response
from django.views.generic import ListView
from django.core.exceptions import ValidationError
from calculation_engine.models import Job, Upload, JobFile, Metrics
from rest_framework import viewsets, status, renderers
from django.http import HttpResponseForbidden
from calculation_engine.serializers import JobSerializer, UploadSerializer
from rest_framework.parsers import FormParser, MultiPartParser
from calculation_engine.tasks import delete_job_files
from silk.profiling.profiler import silk_profile
from rest_framework.permissions import BasePermission
from calculation_engine.log import get_logger
from rest_framework.decorators import action
from calculation_engine.object_store import ObjectStore
from calculation_engine.models import update_job_state
import os
import yaml
from calculation_engine.workflows import Workflow
from django.http import StreamingHttpResponse
from django.core.exceptions import ObjectDoesNotExist
from datetime import datetime, timedelta


logger = get_logger(__name__)

s3 = ObjectStore()


class IsStaff(BasePermission):
    def has_permission(self, request, view):
        return request.user.is_staff


class IsAdmin(BasePermission):
    def has_permission(self, request, view):
        return request.user.is_superuser


def launch_workflow(request_config={}, job_id=''):
    update_job_state(job_id, Job.JobStatus.PENDING)
    wf_config = request_config['workflow']['config']
    logger.debug(f'''Workflow config:\n{yaml.dump(wf_config, indent=2)}''')
    wf = Workflow(config=wf_config, job_id=job_id)
    logger.debug(f'''Workflow object:\n{wf}''')
    logger.debug('''Running workflow...''')
    wf.run_workflow()


class JobViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows jobs to be viewed or edited.
    """
    model = Job
    serializer_class = JobSerializer
    permission_classes = [IsStaff | IsAdmin]

    def get_queryset(self):
        if self.request.user.is_superuser:
            queryset = Job.objects.all()
        else:
            queryset = Job.objects.filter(owner__exact=self.request.user)
        return queryset

    @silk_profile(name='Create Job')
    def create(self, request, *args, **kwargs):
        logger.debug(f'Creating job from request: {request.data}')
        # Create the Job table record
        response = super().create(request, args, kwargs)
        uuid = response.data['uuid']
        job = Job.objects.get(uuid__exact=uuid)
        job.owner = request.user
        job.save()
        # Launch workflow as async Celery tasks
        try:
            request_config = job.config
        except Exception as e:
            logger.error(f'''Error: {e}''')
            response.status_code = status.HTTP_400_BAD_REQUEST
            response.data = f'''{e}'''
            return response
        logger.debug(f'''Launching Celery task for workflow "{job.name}"...''')
        try:
            launch_workflow(request_config=request_config, job_id=uuid)
        except Exception as err:
            err_msg = f'Failed to launch workflow: {err}'
            logger.error(err_msg)
            response.status_code = status.HTTP_400_BAD_REQUEST
            response.data = f'''{err_msg}'''
        return response

    def destroy(self, request, pk=None, *args, **kwargs):
        # TODO: We may want to create new records in a "deleted_job" table for analysis purposes,
        #       or perhaps there is a dedicated "stats" table with hook functions on operations
        #       to track usage.
        # TODO: Revoke Celery task if job is still running. This is not working. Getting errors like:
        #       ERROR/MainProcess] pidbox command error: TypeError('sequence item 0: 
        #       expected str instance, UUID found')
        # instance = self.get_object()
        # task_id = instance.uuid
        # try:
        #     result = AsyncResult(task_id)
        #     result.revoke()
        # except Exception as e:
        #     logger.error(f'''{e}''')
        response = Response()
        job_id = pk
        logger.info(f'''Deleting job "{job_id}"...''')
        # Delete job files
        delete_job_files.delay(job_id)
        # Delete job record from database
        response = super().destroy(request, job_id, args, kwargs)
        return response

    def partial_update(self, request, pk=None, *args, **kwargs):
        response = Response()
        uuid = pk
        try:
            job = self.get_queryset().filter(uuid__exact=uuid)
        except ValidationError:
            response.data = 'Invalid UUID.'
            response.status_code = status.HTTP_400_BAD_REQUEST
            return response
        if not job:
            response.data = f'Job {uuid} not found or not job owner.'
            response.status_code = status.HTTP_404_NOT_FOUND
            return response
        response = super().partial_update(request, uuid, args, kwargs)
        return response


class JobListView(ListView):

    model = Job
    permission_classes = [IsStaff | IsAdmin]
    template_name = 'calculation_engine/job_list.html'

    def handle_no_permission(self):
        return HttpResponseForbidden(content='You must be authenticated.')

    def get_queryset(self):
        if self.request.user.is_superuser:
            queryset = super().get_queryset()
        else:
            queryset = super().get_queryset().filter(owner__exact=self.request.user)
        return queryset


class PassthroughRenderer(renderers.BaseRenderer):
    """
        Return data as-is. View should supply a Response.
    """
    media_type = ''
    format = ''

    def render(self, data, accepted_media_type=None, renderer_context=None):
        return data


class JobFileDownloadViewSet(viewsets.ViewSet):

    permission_classes = [IsStaff | IsAdmin]

    def download(self, request, job_id=None, file_path=None, *args, **kwargs):
        job_id = str(job_id)
        file_path = file_path.strip('/')
        obj_key = os.path.join('/jobs', job_id, file_path)
        file_path = os.path.join('/', file_path)
        response = Response()
        job_file = JobFile.objects.filter(job__owner__exact=self.request.user,
                                          job__uuid__exact=job_id,
                                          path__exact=file_path)
        if not job_file:
            response.data = f'File "{file_path}" not found for job {job_id}.'
            response.status_code = status.HTTP_404_NOT_FOUND
            return response
        job_file = job_file[0]

        obj = s3.get_object(obj_key)
        obj_body = obj['Body']
        logger.debug(obj_body)
        response = StreamingHttpResponse(streaming_content=obj_body.iter_chunks())
        response['Content-Disposition'] = 'attachment; filename="%s"' % os.path.basename(file_path)
        return response


class UploadDownloadViewSet(viewsets.ViewSet):

    permission_classes = [IsStaff | IsAdmin]

    # def get_queryset(self):
    #     if self.request.user.is_superuser:
    #         queryset = Upload.objects.all()
    #     else:
    #         queryset = Upload.objects.filter(owner__exact=self.request.user)
    #     return queryset

    def download(self, request, upload_id=None, *args, **kwargs):
        response = Response(
            status=status.HTTP_200_OK,
        )
        upload_id = str(upload_id)
        uploaded_file = Upload.objects.filter(uuid__exact=upload_id)
        try:
            uploaded_file = Upload.objects.get(uuid__exact=upload_id)
            assert uploaded_file.owner == request.user or uploaded_file.public
        except (ObjectDoesNotExist, AssertionError):
            response = Response(
                status=status.HTTP_404_NOT_FOUND,
                data=f'Upload {upload_id} not found or is private.')
            return response
        # get an open file handle
        file_handle = uploaded_file.file.open()

        # send file
        response = StreamingHttpResponse(streaming_content=file_handle)
        response['Content-Disposition'] = 'attachment; filename="%s"' % uploaded_file.file.name
        return response


class UploadViewSet(viewsets.ModelViewSet):
    parser_classes = (MultiPartParser, FormParser)
    serializer_class = UploadSerializer
    permission_classes = [IsStaff | IsAdmin]
    queryset = Upload.objects.all()
    # def get_queryset(self):
    #     if self.request.user.is_superuser:
    #         queryset = Upload.objects.all()
    #     else:
    #         queryset = Upload.objects.filter(owner__exact=self.request.user)
    #     return queryset

    def destroy(self, request, pk=None):
        response = Response()
        uuid = pk
        if uuid:
            uploaded_file = self.get_queryset().filter(uuid__exact=uuid)
        else:
            response.data = 'uuid must be specified.'
            response.status_code = status.HTTP_400_BAD_REQUEST
            return response
        if not uploaded_file:
            response.data = f'File {uuid} not found.'
            response.status_code = status.HTTP_404_NOT_FOUND
            return response
        uploaded_file = uploaded_file[0]
        logger.info(f'''Deleting uploaded file "{uploaded_file.path}" ("{uploaded_file.uuid}")...''')
        uploaded_file_path = os.path.join('uploads', str(uploaded_file.file))
        logger.debug(uploaded_file_path)
        s3.delete_directory(uploaded_file_path)
        uploaded_file.delete()
        response.data = f'File {uploaded_file.path} deleted.'
        response.status_code = status.HTTP_200_OK
        return response

    def create(self, request):
        response = Response()
        logger.debug(request.data)
        serializer = self.serializer_class(data=request.data)
        if not serializer.is_valid():
            response.data = serializer.errors
            response.status_code = status.HTTP_400_BAD_REQUEST
            return response
        logger.debug(serializer.validated_data)
        user_path = serializer.validated_data['path']

app/calculation_engine/templates/calculation_engine/home.html
{% extends 'app_base/base.html' %}
{% load static %}
{% block content %}

<div class="container">
  <div class="row align-items-end">
    <div class="col-lg-5">
      <img src="{% static 'images/Muses_Full_Color_banner.png' %}" style="max-height: 150px;" />
    </div>
  </div>
  <div class="row align-items-end">
    <div class="col-lg-5">
      <h4 class="slogan">
        Calculation Engine // Alpha Release
      </h4>
    </div>
  </div>
  <div class="row pt-3">
    <div class="col-lg-12">
      <div class="pb-3">
        <a href="https://musesframework.io/docs/" target="_blank" role="button" class="btn btn-primary">
          Read the docs <i class="bi bi-book-half"></i><i class="bi bi-book-half"></i>
        </a>
      </div>
      <p>
        Welcome to the MUSES Calculation Engine!
      </p>
    </div>
  </div>
</div>

{% endblock %}

app/calculation_engine/templates/calculation_engine/job_list.html
{% extends 'app_base/base.html' %}
{% block content %}
  <h1>Jobs</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Time Created</th>
          <th>UUID</th>
          <th>Status</th>
          <th>Saved</th>
          <th>Public</th>
          <th>Error</th>
          {% if user.is_superuser %}
          <th>Owner</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% if job_list %}
        {% for this_job in job_list %}
        <tr>
          <td>{{ this_job.name }}</td>
          <td>{{ this_job.created }}</td>
          <td class="uuid-table"><code>{{ this_job.uuid }}</code></td>
          <td>{{ this_job.status }}</td>
          <td>{{ this_job.saved }}</td>
          <td>{{ this_job.public }}</td>
          {% if this_job.error_info %}
          <td>
            <div class="error-msg"><code>{{ this_job.error_info }}</code></div>
          </td>
          {% else %}
          <td></td>
          {% endif %}
          {% if user.is_superuser %}
          <td>{{ this_job.owner }}</td>
          {% endif %}
        </tr>
        {% endfor %}
        {% endif %}
    </tbody>
  </table>

{% endblock %}

app/calculation_engine/templates/calculation_engine/metrics.html
{% extends 'app_base/base.html' %}
{% block content %}
  <h1>Metrics</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Time</th>
          <th>Jobs (success/failure)</th>
          <th>Job files (size)</th>
          <th>Uploads</th>
          <th>Users (active)</th>
          <th>Users (total)</th>
        </tr>
      </thead>
      <tbody>
        {% if metrics_list %}
        {% for this_metric in metrics_list %}
        <tr>
          <td class="uuid-table"><code>{{ this_metric.time_collected }}</code></td>
          <td class="uuid-table"><code>{{ this_metric.jobs_total }} ({{ this_metric.jobs_success }}/{{ this_metric.jobs_failure }})</code></td>
          <td class="uuid-table"><code>{{ this_metric.job_files_total }} ({{ this_metric.job_files_size }} {{ this_metric.job_files_size_units }})</code></td>
          <td class="uuid-table"><code>{{ this_metric.uploads_total }}</code></td>
          <td class="uuid-table"><code>{{ this_metric.users_active }}</code></td>
          <td class="uuid-table"><code>{{ this_metric.users_count}}</code></td>
        </tr>
        {% endfor %}
        {% endif %}
    </tbody>
  </table>

{% endblock %}

app/calculation_engine/templates/calculation_engine/swagger-ui.html
<!DOCTYPE html>
<html>
  <head>
    <title>Swagger</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
    <script>
    const ui = SwaggerUIBundle({
        url: "{% url schema_url %}",
        dom_id: '#swagger-ui',
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
        layout: "BaseLayout",
        requestInterceptor: (request) => {
          request.headers['X-CSRFToken'] = "{{ csrf_token }}"
          return request;
        }
      })
    </script>
  </body>
</html>

app/calculation_engine/templates/calculation_engine/upload_list.html
{% extends 'app_base/base.html' %}
{% block content %}
  <h1>Uploaded files</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Path</th>
          <th>Description</th>
          <th>UUID</th>
          <th>Time Uploaded</th>
          <th>Public</th>
          <th>Link</th>
          {% if user.is_superuser %}
          <th>Owner</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% if upload_list %}
        {% for this_upload in upload_list %}
        <tr>
          <td class="uuid-table"><code>{{ this_upload.path }}</code></td>
          <td class="">{{ this_upload.description }}</td>
          <td class="uuid-table"><code>{{ this_upload.uuid }}</code></td>
          <td>{{ this_upload.created }}</td>
          <td>{{ this_upload.public }}</td>
          <td>
            <form action="{% url 'download-upload' this_upload.uuid %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-link" style="padding: 0;">Download</button>
            </form>
          </td>
          {% if user.is_superuser %}
          <td>{{ this_upload.owner }}</td>
          {% endif %}
        </tr>
        {% endfor %}
        {% endif %}
    </tbody>
  </table>

{% endblock %}